/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Pamela
 */
public class PanelSumar extends javax.swing.JPanel {
    
    Controlador miControlador; 
    
    /**
     * Creates new form PanelSuma
     */
    public PanelSumar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        matrizA11 = new javax.swing.JTextField();
        matrizA12 = new javax.swing.JTextField();
        matrizA13 = new javax.swing.JTextField();
        matrizA14 = new javax.swing.JTextField();
        matrizA15 = new javax.swing.JTextField();
        matrizA21 = new javax.swing.JTextField();
        matrizA22 = new javax.swing.JTextField();
        matrizA23 = new javax.swing.JTextField();
        matrizA24 = new javax.swing.JTextField();
        matrizA25 = new javax.swing.JTextField();
        matrizA31 = new javax.swing.JTextField();
        matrizA32 = new javax.swing.JTextField();
        matrizA33 = new javax.swing.JTextField();
        matrizA34 = new javax.swing.JTextField();
        matrizA35 = new javax.swing.JTextField();
        matrizA41 = new javax.swing.JTextField();
        matrizA42 = new javax.swing.JTextField();
        matrizA43 = new javax.swing.JTextField();
        matrizA44 = new javax.swing.JTextField();
        matrizA45 = new javax.swing.JTextField();
        matrizA51 = new javax.swing.JTextField();
        matrizA52 = new javax.swing.JTextField();
        matrizA53 = new javax.swing.JTextField();
        matrizA54 = new javax.swing.JTextField();
        matrizA55 = new javax.swing.JTextField();
        matrizB11 = new javax.swing.JTextField();
        matrizB12 = new javax.swing.JTextField();
        matrizB13 = new javax.swing.JTextField();
        matrizB14 = new javax.swing.JTextField();
        matrizB15 = new javax.swing.JTextField();
        matrizB21 = new javax.swing.JTextField();
        matrizB22 = new javax.swing.JTextField();
        matrizB23 = new javax.swing.JTextField();
        matrizB24 = new javax.swing.JTextField();
        matrizB25 = new javax.swing.JTextField();
        matrizB31 = new javax.swing.JTextField();
        matrizB32 = new javax.swing.JTextField();
        matrizB33 = new javax.swing.JTextField();
        matrizB34 = new javax.swing.JTextField();
        matrizB35 = new javax.swing.JTextField();
        matrizB41 = new javax.swing.JTextField();
        matrizB42 = new javax.swing.JTextField();
        matrizB43 = new javax.swing.JTextField();
        matrizB44 = new javax.swing.JTextField();
        matrizB45 = new javax.swing.JTextField();
        matrizB51 = new javax.swing.JTextField();
        matrizB52 = new javax.swing.JTextField();
        matrizB53 = new javax.swing.JTextField();
        matrizB54 = new javax.swing.JTextField();
        matrizB55 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSumar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarResultado = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Matriz A");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Matriz B");

        matrizA11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizA11ActionPerformed(evt);
            }
        });

        matrizA42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrizA42ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("+");

        btnSumar.setText("Calcular Suma");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        mostrarResultado.setColumns(20);
        mostrarResultado.setRows(5);
        jScrollPane1.setViewportView(mostrarResultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSumar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(matrizA51)
                                            .addComponent(matrizA41)
                                            .addComponent(matrizA31)
                                            .addComponent(matrizA21)
                                            .addComponent(matrizA11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(matrizA42)
                                            .addComponent(matrizA32)
                                            .addComponent(matrizA22)
                                            .addComponent(matrizA12)
                                            .addComponent(matrizA52, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(matrizA13, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(matrizA23, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(matrizA33, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(matrizA43, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(matrizA53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(matrizA14)
                                            .addComponent(matrizA24)
                                            .addComponent(matrizA34)
                                            .addComponent(matrizA44)
                                            .addComponent(matrizA54, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(matrizA15)
                                            .addComponent(matrizA25)
                                            .addComponent(matrizA35)
                                            .addComponent(matrizA45)
                                            .addComponent(matrizA55, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(matrizB21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matrizB31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matrizB11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matrizB41, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(matrizB51, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matrizB22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB42, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB52, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matrizB23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB43, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB53, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matrizB24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB44, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB54, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matrizB25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB45, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matrizB55, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(688, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matrizA12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matrizA22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(matrizA32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(matrizA33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(matrizA34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(matrizA35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(matrizB31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(matrizB32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(matrizB33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(matrizB34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(matrizB35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matrizA42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(matrizA52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizA55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matrizB55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(matrizA11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(matrizA21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(matrizA31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(matrizA41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(matrizA51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSumar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jScrollPane2.setViewportView(jPanel1);

        add(jScrollPane2);
    }// </editor-fold>//GEN-END:initComponents

    public String getMatrizA11(){
        return matrizA11.getText();
    }
    
    public String getMatrizA12(){
        return matrizA12.getText();
    }
    
    public String getMatrizA13(){
        return matrizA13.getText();
    }
    
    public String getMatrizA14(){
        return matrizA14.getText();
    }
    
    public String getMatrizA15(){
        return matrizA15.getText();
    }
    
    public String getMatrizA21(){
        return matrizA21.getText();
    }
    
    public String getMatrizA22(){
        return matrizA22.getText();
    }
    
    public String getMatrizA23(){
        return matrizA23.getText();
    }
    
    public String getMatrizA24(){
        return matrizA24.getText();
    }
    
    public String getMatrizA25(){
        return matrizA25.getText();
    }
    
    public String getMatrizA31(){
        return matrizA31.getText();
    }
    
    public String getMatrizA32(){
        return matrizA32.getText();
    }
    
    public String getMatrizA33(){
        return matrizA33.getText();
    }
    
    public String getMatrizA34(){
        return matrizA34.getText();
    }
    
    public String getMatrizA35(){
        return matrizA35.getText();
    }
    
    public String getMatrizA41(){
        return matrizA41.getText();
    }
    
    public String getMatrizA42(){
        return matrizA42.getText();
    }
    
    public String getMatrizA43(){
        return matrizA43.getText();
    }
    
    public String getMatrizA44(){
        return matrizA44.getText();
    }
    
    public String getMatrizA45(){
        return matrizA45.getText();
    }
    
    public String getMatrizA51(){
        return matrizA51.getText();
    }
    
    public String getMatrizA52(){
        return matrizA52.getText();
    }
    
    public String getMatrizA53(){
        return matrizA53.getText();
    }
    
    public String getMatrizA54(){
        return matrizA54.getText();
    }
    
    public String getMatrizA55(){
        return matrizA55.getText();
    }
    
    public String getMatrizB11(){
        return matrizB11.getText();
    }
    
    public String getMatrizB12(){
        return matrizB12.getText();
    }
    
    public String getMatrizB13(){
        return matrizB13.getText();
    }
    
    public String getMatrizB14(){
        return matrizB14.getText();
    }
    
    public String getMatrizB15(){
        return matrizB15.getText();
    }
    
    public String getMatrizB21(){
        return matrizB21.getText();
    }
    
    public String getMatrizB22(){
        return matrizB22.getText();
    }
    
    public String getMatrizB23(){
        return matrizB23.getText();
    }
    
    public String getMatrizB24(){
        return matrizB24.getText();
    }
    
    public String getMatrizB25(){
        return matrizB25.getText();
    }
    
    public String getMatrizB31(){
        return matrizB31.getText();
    }
    
    public String getMatrizB32(){
        return matrizB32.getText();
    }
    
    public String getMatrizB33(){
        return matrizB33.getText();
    }
    
    public String getMatrizB34(){
        return matrizB34.getText();
    }
    
    public String getMatrizB35(){
        return matrizB35.getText();
    }
    
    public String getMatrizB41(){
        return matrizB41.getText();
    }
    
    public String getMatrizB42(){
        return matrizB42.getText();
    }
    
    public String getMatrizB43(){
        return matrizB43.getText();
    }
    
    public String getMatrizB44(){
        return matrizB44.getText();
    }
    
    public String getMatrizB45(){
        return matrizB45.getText();
    }
    
    public String getMatrizB51(){
        return matrizB51.getText();
    }
    
    public String getMatrizB52(){
        return matrizB52.getText();
    }
    
    public String getMatrizB53(){
        return matrizB53.getText();
    }
    
    public String getMatrizB54(){
        return matrizB54.getText();
    }
    
    public String getMatrizB55(){
        return matrizB55.getText();
    }
    
    public void setCalcSolucion(double[][] solucion){
        mostrarResultado.setText(String.valueOf(solucion));
    }
    
    public void addCalculadoraListener(ActionListener listenforBtnSumar){
        btnSumar.addActionListener(listenforBtnSumar);
    }
    
    public void displayErrorMessage(String mensajeError){
        JOptionPane.showMessageDialog(this, mensajeError); 
    }
    
    public void setControlador(Controlador controlador){
        miControlador = controlador; 
    }
    
    private void matrizA42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizA42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizA42ActionPerformed

    private void matrizA11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrizA11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrizA11ActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSumarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField matrizA11;
    private javax.swing.JTextField matrizA12;
    private javax.swing.JTextField matrizA13;
    private javax.swing.JTextField matrizA14;
    private javax.swing.JTextField matrizA15;
    private javax.swing.JTextField matrizA21;
    private javax.swing.JTextField matrizA22;
    private javax.swing.JTextField matrizA23;
    private javax.swing.JTextField matrizA24;
    private javax.swing.JTextField matrizA25;
    private javax.swing.JTextField matrizA31;
    private javax.swing.JTextField matrizA32;
    private javax.swing.JTextField matrizA33;
    private javax.swing.JTextField matrizA34;
    private javax.swing.JTextField matrizA35;
    private javax.swing.JTextField matrizA41;
    private javax.swing.JTextField matrizA42;
    private javax.swing.JTextField matrizA43;
    private javax.swing.JTextField matrizA44;
    private javax.swing.JTextField matrizA45;
    private javax.swing.JTextField matrizA51;
    private javax.swing.JTextField matrizA52;
    private javax.swing.JTextField matrizA53;
    private javax.swing.JTextField matrizA54;
    private javax.swing.JTextField matrizA55;
    private javax.swing.JTextField matrizB11;
    private javax.swing.JTextField matrizB12;
    private javax.swing.JTextField matrizB13;
    private javax.swing.JTextField matrizB14;
    private javax.swing.JTextField matrizB15;
    private javax.swing.JTextField matrizB21;
    private javax.swing.JTextField matrizB22;
    private javax.swing.JTextField matrizB23;
    private javax.swing.JTextField matrizB24;
    private javax.swing.JTextField matrizB25;
    private javax.swing.JTextField matrizB31;
    private javax.swing.JTextField matrizB32;
    private javax.swing.JTextField matrizB33;
    private javax.swing.JTextField matrizB34;
    private javax.swing.JTextField matrizB35;
    private javax.swing.JTextField matrizB41;
    private javax.swing.JTextField matrizB42;
    private javax.swing.JTextField matrizB43;
    private javax.swing.JTextField matrizB44;
    private javax.swing.JTextField matrizB45;
    private javax.swing.JTextField matrizB51;
    private javax.swing.JTextField matrizB52;
    private javax.swing.JTextField matrizB53;
    private javax.swing.JTextField matrizB54;
    private javax.swing.JTextField matrizB55;
    private javax.swing.JTextArea mostrarResultado;
    // End of variables declaration//GEN-END:variables
}
